#!/bin/sh
#
# mysql-mmm-agent    This shell script takes care of starting and stopping
#                    the mmm agent daemon.
#
# chkconfig:	- 64 36
# description: MMM Agent.
# processname: mmm_agentd
# config: /etc/mysql-mmm/mmm_agent.conf
# pidfile: /var/run/mysql-mmm/mmm_agentd.pid
#
# $Id$

# Source function library
. /etc/rc.d/init.d/functions

# Get network config
. /etc/sysconfig/network

# Check that networking is up.
if is_yes "${NETWORKING}"; then
	if [ ! -f /var/lock/subsys/network -a "$1" != stop -a "$1" != status ]; then
		msg_network_down "MMM Agent Daemon"
		exit 1
	fi
else
	exit 0
fi

# Set defaults
ENABLED="no"

# Get service config - may override defaults
[ -f /etc/sysconfig/mysql-mmm-agent ] && . /etc/sysconfig/mysql-mmm-agent

# configtest itself
# must return non-zero if check failed
# output is discarded if checkconfig is ran without details
configtest() {
	if ! is_yes "${ENABLED}"; then
		echo "MMM Agent Daemon is disabled!"
		return 1
	fi
	return 0
}

# wrapper for configtest
checkconfig() {
	local details=${1:-0}

	if [ $details = 1 ]; then
		# run config test and display report (status action)
		show "Checking %s configuration" "MMM Agent Daemon"; busy
		local out
		out=$(configtest 2>&1)
		RETVAL=$?
		if [ $RETVAL = 0 ]; then
			ok
		else
			fail
		fi
		[ "$out" ] && echo >&2 "$out"
	else
		# run config test and abort with nice message if failed
		# (for actions checking status before action).
		configtest >/dev/null 2>&1
		RETVAL=$?
		if [ $RETVAL != 0 ]; then
			show "Checking %s configuration" "MMM Agent Daemon"; fail
			nls 'Configuration test failed. See details with %s "checkconfig"' $0
			exit $RETVAL
		fi
	fi
}

start() {
	# Check if the service is already running?
	if [ -f /var/lock/subsys/mysql-mmm-agent ]; then
		msg_already_running "MMM Agent Daemon"
		return
	fi

	checkconfig
	msg_starting "MMM Agent Daemon"
	daemon /usr/sbin/mysql-mmm-agent
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/mysql-mmm-agent
}

stop() {
	if [ ! -f /var/lock/subsys/mysql-mmm-agent ]; then
		msg_not_running "MMM Agent Daemon"
		return
	fi

	# Stop daemons.
	msg_stopping "MMM Agent Daemon"
	killproc --pidfile /var/run/mysql-mmm-agent.pid mmm_agentd -TERM
	rm -f /var/lock/subsys/mysql-mmm-agent
}

condrestart() {
	if [ ! -f /var/lock/subsys/mysql-mmm-agent ]; then
		msg_not_running "MMM Agent Daemon"
		RETVAL=$1
		return
	fi

	checkconfig
	stop
	start
}

RETVAL=0
# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	checkconfig
	stop
	start
	;;
  try-restart)
	condrestart 0
	;;
  force-reload)
	condrestart 7
	;;
  checkconfig|configtest)
	checkconfig 1
	;;
  status)
	status --pidfile /var/run/mysql-mmm-agent.pid mysql-mmm-agent mmm_agentd
	RETVAL=$?
	;;
  *)
	msg_usage "$0 {start|stop|restart|try-restart|force-reload|checkconfig|status}"
	exit 3
esac

exit $RETVAL
